#!/bin/bash
sed "s/<BbcUserID>/$(whoami)/g" <./.m2/settings.off-network.xml >~/.m2/settings.off-network.xml
sed "s/<BbcUserID>/$(whoami)/g" <./.m2/settings.on-network.xml >~/.m2/settings.on-network.xml
