#!/bin/bash
echo What is your cosmos username?

read cosmos_username

sed "s/<Your Cosmos Username>/$cosmos_username/g" <./.ssh/config.off-network >~/.ssh/config.off-network
sed "s/<Your Cosmos Username>/$cosmos_username/g" <./.ssh/config.on-network >~/.ssh/config.on-network
